### ISSUE TITLE
The settings icon is not shown on Chrome macOS

### ISSUE THREAD

**Issue by tete1030** [remnoteio/remnote-issues#42]
**Describe the bug**
The settings icon is not shown on Chrome for macOS, while being normal on Safari or Chrome for windows

**To Reproduce**
1. Open remnote

**Expected behavior**
The sidebar should be wide enough to show the settings icon

**Screenshots**
![image](https://user-images.githubusercontent.com/4312115/90160091-e515e500-ddc3-11ea-9534-fa25f5e5900c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Catalina
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 84

**Additional context**

**Comment by moritzWa** [comment]
I could not replicate this issue. Please help us through answering some questions:

1) Any extensions that could be interfering?
2) Any custom css?
3) Also in incognito window?
4) Also with all zoom levels?

**Comment by tete1030** [comment]
Hi, I have tried incognito mode, and also new profile in chrome without any extensions. The problem persists.

The zoom level is 100% on mac. But the problem disappears after I set zoom level to any value >= 125%

My screen is retina display, resolution 2880x1800.  The culprit might be `max-width: 240px;` for `#document-sidebar`

I also want to note that, my windows chrome has default zoom level set to 110%. So I didn't notice it in Windows. If I set the level back to 100%, similar problem appears.

**Comment by tete1030** [comment]
These are widths of each button, extracted using the following script
```javascript
$('#document-sidebar__bottom-menu--buttons').children().map((i,e)=>e.getClientRects()[0].width).toArray()
```

mac:
```
[73.171875, 51.71875, 67.84375, 56.453125, 20]
```

windows:
```
[68.921875, 47.625, 63.75, 55.265625, 20]
```

Another finding:
On safari, there is an extra class, `DocumentPageSidebar`, for `#document-sidebar`. This class has set `max-width` to `300px!important`. However, this class does not exist on chrome.

Safari:
![image](https://user-images.githubusercontent.com/4312115/90305330-083fb200-def4-11ea-9de1-412149122588.png)

Chrome:
![image](https://user-images.githubusercontent.com/4312115/90305346-32916f80-def4-11ea-9396-6544df41c1d4.png)

**Comment by mfranzs** [comment]
Thanks for the extra info! Where does this happen?
A) Only on the tutorial pages
B) Only on your personal documents
C) Both

**Comment by tete1030** [comment]
I see! Didn't know there is difference between A and B. They were mostly under B but some were under A. But this only annuls the `DocumentationPageSidebar` part I reported. All other info remain the same.

Now I tested all under A (with zoom 100%) and their widths are
```
Chrome (mac):             [73.171875, 51.71875, 67.84375, 56.453125, 20]
Chrome (win):             [68.921875, 47.625, 63.75, 55.265625, 20]
Safari (mac, no problem): [64.953125, 46.609375, 60.28125, 50.546875, 20]
```

I think this is relevant to the fonts browsers are using to render. Here are `Rendered Fonts` in dev tools in chrome, and extracted font info from _WhatFont_ extension in Safari
```
Chrome (mac): .SF NS
Chrome (windows): Segoe UI
Safari (mac, no problem): -apple-system
```

**Comment by moritzWa** [comment]
This should be fixed in the next update.

**Comment by mfranzs** [comment]
Thanks for the report - we've deployed a fix. Please let us know if you're still encountering problems!

**Comment by tete1030** [comment]
Thanks for your help. But the problem is hardly fixed. It seems that the only changes are enlarging the setting button and centering all buttons, which increase the chance of setting button's exposure, but certainly `240px` is still not enough for showing them. 

I understand that this minor problem does not worth big changes currently, and you have many other priorities for new features and functional bugs. Current fix has make it to some extent usable. So no need to hurry on this.

![image](https://user-images.githubusercontent.com/4312115/90855099-3bc98300-e3b1-11ea-9922-c60fd9eaeb67.png)
